### PR TITLE
feat(cli): add silent mode

### PR DESCRIPTION
**Pull request by tooppaaa**
#31

This adds --silent to the cli in preparation of others features

### CODE REVIEW

**Comment by obahareth** [comment]
@tooppaaa Awesome work! Do you think you could fix the failing tests? It would be great if you could also add tests for the silent mode? but I can take care of that later if not.

**Comment by tooppaaa** [comment]
Yep sure, I have some error while launching them locally.
I haven't really looked why to be honest. :)

**Comment by obahareth** [comment]
Awesome work @tooppaaa, releasing a new build to NPM now!

**Comment by obahareth** [comment]
Released as 1.4.0

**Pull request merged**
