### PR TITLE
Core: Node API was not calling right method

### PR DESCRIPTION
**Pull request by tooppaaa**

### CODE REVIEW

**Comment by tooppaaa** [comment]
Previous one was merged a bit too fast ;)

**Comment by obahareth** [comment]
@tooppaaa We should release a new version for this I assume, right? `2.0.1`?

**Comment by obahareth** [comment]
By the way @tooppaaa can you share your npmjs.com username with me? I'd like to add you to the package on there as well.

**Comment by tooppaaa** [comment]
Hey @obahareth no worries :)
My username is the same as github: tooppaaa

Yes, we can release :)

**Comment by varoot** [comment]
Can we release this and also update the documentation on README to remove reference to `result.es6Modules`?

**Comment by tooppaaa** [comment]
@varoot Sorry I didn't get (saw !?) a notification when I was added to npm for this package.
This is (should) be deployed.

Could you please let me know as it's my first time publishing this package if it's all good on your side ?
Thanks a lot !!

**Comment by varoot** [comment]
> Could you please let me know as it's my first time publishing this package if it's all good on your side ?

@tooppaaa  Yep. It's working now. Thanks a lot!

**Comment by obahareth** [comment]
> Can we release this and also update the documentation on README to remove reference to `result.es6Modules`?

@tooppaaa @varoot I'm a little confused on this part, I think we need this? The functions that build the regex expect an array of strings and that should be `result.es6Modules`, no? Because `result` is just an object, e.g. see #39.

**Comment by varoot** [comment]
Hmm... I think there must be another PR to change this behavior. Previously it was returning array of strings.

**Pull request merged**
